#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps
[ -f "$userresources" ]	&& xrdb -merge "$userresources"
[ -f "$usermodmap" ]	&& xmodmap "$usermodmap"
[ -f "$sysresources" ]	&& xrdb -merge "$sysresources"
[ -f "$sysmodmap" ]		&& xmodmap "$sysmodmap"

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi


[ -f "$HOME/.config/aliasrc" ] && source "$HOME/.config/aliasrc"
[ -f "~/.xprofile" ] && source "~/.xprofile"

exec openbox-session
