#!/bin/sh

alias ~="cd ~" \
	..="cd ../" \
	...="cd ../../" \
	....="cd ../../../" \
	p="sudo pacman" \
	r="ranger" \
	g="git" \
	ls="ls -lht --color=auto --group-directories-first" \
	lsa="ls -alht --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	mo="bash $HOME/.local/bin/mountall" \
	om="bash $HOME/.local/bin/safelyremove" \
	xterm="urxvt"

# to be considered (from https://github.com/LukeSmithxyz/voidrice)
# e="$EDITOR" \
# v="$EDITOR" \
# x="sxiv -ft *" \
# sdn="sudo shutdown -h now" \
# yt="youtube-dl --add-metadata -i -o '%(upload_date)s-%(title)s.%(ext)s'" \
# lsp="pacman -Qett --color=always | less" \
