#!/bin/sh

alias ~="cd ~" \
	..="cd ../" \
	...="cd ../../" \
	....="cd ../../../" \
	p="sudo pacman" \
	g="git" \
	gs="git status" \
	gc="git commit -m" \
	ls="ls -lht --color=auto --group-directories-first" \
	lsa="ls -alht --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	mo="bash $HOME/.local/bin/mountall.sh" \
	om="bash $HOME/.local/bin/safelyremove.sh" \
	dot="bash $HOME/.local/bin/updatedotfiles.sh"

# to be considered (from https://github.com/LukeSmithxyz/voidrice)
# e="$EDITOR" \
# v="$EDITOR" \
# x="sxiv -ft *" \
# sdn="sudo shutdown -h now" \
# ls="ls -hN --color=auto --group-directories-first" \
# yt="youtube-dl --add-metadata -i -o '%(upload_date)s-%(title)s.%(ext)s'" \
# lsp="pacman -Qett --color=always | less" \
